### PR TITLE
Give Leonardo-type arduinos 2048 storage

### PR DESCRIPTION
**Pull request by dhiltonp**
The atmega 32U4 has 2.5K of storage. Let's use it!

### CODE REVIEW

**Comment by dhiltonp** [comment]
The 32U4 doesn't have enough flash for the 2/4Mhz recording options; it has enough to write 1K of space - I've left it at 512 2Mhz, 512 4Mhz.

**Comment by dhiltonp** [comment]
Should I modify ols.profile-agla.cfg to provide up to 2048K, or create a new plugin profile specific to Leonardo?

**Comment by gillham** [comment]
It is better to make a different device profile so that when the client automatically sets the device configuration (based on querying the metadata) it won't select a sample size that is unsupported.
We can easily add 'AGLAL' for example.
Currently the devices are:
AGLA -- Arduino with ATmega328 with 1K sample size ('168 users are special cases so need to manually select the correct sample size)
AGLAM -- Arduino Mega with 7K sample size
AGLAN -- development test of Arduino '328 with Ethernet module and TCP based communication with the client.

I can add:
AGLAL -- Leonardo type (ATmega32U4) devices with 2K sample size.

It needs to be thoroughly tested with 2K sample size to ensure it doesn't run out of memory with the USB code running as well.
I think I have a Leonardo around here, I will have to look for it.

**Comment by dhiltonp** [comment]
OK.

Just so you know, I've been doing my tests using D8 and D9; I haven't tested other pins.

I have also tried triggers, but they haven't been working for me.

**Comment by gillham** [comment]
Can you test the 'agla_leonardo' branch and see how that works?  I can merge those changes into the master at some point after I test with my Leonardo R3.  I think 2048 sample size was a problem before with the debug stuff enabled, but since I disabled the debug by default I merged this change.

**Comment by dhiltonp** [comment]
On that branch:

8 is mapped to channels 3 and 4
9 is mapped to channels 4 and 5
10 is mapped to channels 4 and 5.

No other digital channels are logged.

The triggers don't seem to work.
1K sample size works; 2K sample size hangs (out of memory), even with DEBUG disabled.

---------------

On the now-master
d8 is mapped to ch4
d9 is mapped to ch5
d10 is mapped to ch5
no other pins work.
2K sample size doesn't hang
triggers don't seem to work.

**Comment by dhiltonp** [comment]
Ah, the other pins are on the ICSP header.

**Comment by dhiltonp** [comment]
I was trying to do serial triggers; that's why it wasn't working.

**Pull request merged**
